Repository arduino-libraries/ArduinoRS485, pull requests merged in 2022-12, with the labels that each got.

#33 Fix for inverted pin names in end function
  src/RS485.cpp
Labels: type: imperfection, topic: code

#34 Fix: Arduino Zero does not define A6.
  src/RS485.h
Labels: type: enhancement, topic: code

#35 Explicitly list the supported architectures (samd, mbed_portenta) as verified by CI build.
  library.properties
Labels: type: enhancement, topic: documentation
